name: release

on:
  push:
    # Publish semver tags as releases.
    tags:
      - '!dbg*'
      - '!*-dbg*'
      - '!*-fix*'
      - '*.*.*'

jobs:
  release-windows-amd64:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Choco help
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: -h

    - name: Build
      run: |
        go run cmd/resource/resource.go
        go build -v -trimpath -ldflags "-s -w -H windowsgui" -o  bin/myst-launcher-amd64.exe github.com/mysteriumnetwork/myst-launcher/cmd/app
        go build -v -trimpath -ldflags "-s -w -H windowsgui" -o  bin/myst-launcher-updater.exe github.com/mysteriumnetwork/myst-launcher/cmd/updater
      env:
        GOARCH: amd64
        GOOS: windows

    - name: Sign
      uses: mysteriumnetwork/code-sign-action@v7
      with:
        certificate: '${{ secrets.WINDOWS_CERTS }}'
        password: '${{ secrets.WINDOWS_CERTS_PASSWORD }}'
        certificatesha1: '${{ secrets.WINDOWS_CERTS_THUMBPRINT }}'
        certificatename: '${{ secrets.WINDOWS_CERTS_NAME }}'
        folder: 'bin'
        recursive: true

    - name: Build
      run: |
        choco install iconsext
        choco install wix
        $env:PATH=$env:PATH+";C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files (x86)\NirSoft\IconsExtract"
        iconsext.exe /save "bin\myst-launcher-amd64.exe" "installer\" -icons
        candle installer\installer.wxs installer\licenseDialogue.wxs  -arch x64 -out installer\
        light installer\installer.wixobj installer\licenseDialogue.wixobj -dcl:high -ext WixUIExtension.dll -ext WixUtilExtension.dll -out installer\myst-launcher-x64.msi

    - name: Sign
      uses: mysteriumnetwork/code-sign-action@v7
      with:
        certificate: '${{ secrets.WINDOWS_CERTS }}'
        password: '${{ secrets.WINDOWS_CERTS_PASSWORD }}'
        certificatesha1: '${{ secrets.WINDOWS_CERTS_THUMBPRINT }}'
        certificatename: '${{ secrets.WINDOWS_CERTS_NAME }}'
        folder: 'installer'
        recursive: true

    - name: Upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: |
          bin/myst-launcher-updater.exe
          installer/myst-launcher-x64.msi

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}